Выполнил задание. Добавил имя наставника и ссылку на профиль
htmlacademy-htmlcss/1123705-device-30 pull request #1
Opened 2021-01-19 05:21 UTC by TroyGod

2021-02-01 21:50 UTC, dean992008 requested changes

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +    <nav>
В `nav` нужно обернуть только главное меню.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +      <form action="" method="POST">
Форму поиска нужно отправить с пощью get, чтобы можно было скопировать сылку на результаты поиска.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +          Каталог товаров
`Каталог товаров` нужно обернуть в ссылку

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +            <ul>
Пагинацию нужно вынести на пределы слайдера, а потом мы спозиционируем вбсолютно.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +        <li>
В слоях есть есть 2 слайда, их тоже нужно сверстать.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +        <li></li>
еще 2 слайда есть в слоях, тоже нужно написать.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +          <img src="https://via.placeholder.com/150x100" width="150" height="150" alt="Логотип компании dji">
Лого производителей нужно обернуть в сылки.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +    <button type="button">Закрыть</button>
Кнопку я бы перенес в форму и сделал `type="reset"`, чтобы при закрытии формы она очищялась.

2021-02-01 21:50 UTC, dean992008 commented on index.html
> +      <p>
Контролы формы лучше обернуть в список.

2021-02-01 21:50 UTC, dean992008 commented on catalog.html
> +          <button type="button">Назад</button>
Это тоже должны быть сылки.

2021-02-02 11:43 UTC, TroyGod commented on index.html
> +    <nav>
А что подразумевается под главным меню? Вроде логотипа нет в блоке. Или вы имеете в виду, что в nav обернуть только список с пунктами Доставка, Гарантия, Контакты?

2021-02-02 11:50 UTC, TroyGod commented on catalog.html
> +          <button type="button">Назад</button>
Здесь непонятно. Кнопки находятся внутри списков

2021-02-04 09:43 UTC, merged